Mounted at /content/drive
aa
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_1 (InputLayer)        [(None, 100, 1710, 1)]    0         
                                                                 
 conv2d (Conv2D)             (None, 100, 1710, 64)     640       
                                                                 
 batch_normalization (BatchN  (None, 100, 1710, 64)    256       
 ormalization)                                                   
                                                                 
 re_lu (ReLU)                (None, 100, 1710, 64)     0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 50, 855, 64)      0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 50, 855, 64)       36928     
                                                                 
 batch_normalization_1 (Batc  (None, 50, 855, 64)      256       
 hNormalization)                                                 
                                                                 
 re_lu_1 (ReLU)              (None, 50, 855, 64)       0         
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 25, 427, 64)      0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 25, 427, 128)      73856     
                                                                 
 batch_normalization_2 (Batc  (None, 25, 427, 128)     512       
 hNormalization)                                                 
                                                                 
 re_lu_2 (ReLU)              (None, 25, 427, 128)      0         
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 12, 213, 128)     0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 12, 213, 128)      147584    
                                                                 
 batch_normalization_3 (Batc  (None, 12, 213, 128)     512       
 hNormalization)                                                 
                                                                 
 re_lu_3 (ReLU)              (None, 12, 213, 128)      0         
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 6, 106, 128)      0         
 2D)                                                             
                                                                 
 lambda (Lambda)             (None, 106, 6, 128)       0         
                                                                 
 reshape (Reshape)           (None, 106, 768)          0         
                                                                 
 dropout (Dropout)           (None, 106, 768)          0         
                                                                 
 bidirectional (Bidirectiona  (None, 106, 1024)        5246976   
 l)                                                              
                                                                 
 dropout_1 (Dropout)         (None, 106, 1024)         0         
                                                                 
 dense (Dense)               (None, 106, 1782)         1826550   
                                                                 
=================================================================
Total params: 7,334,070
Trainable params: 7,333,302
Non-trainable params: 768
_________________________________________________________________
Epoch 1/10
2284/2284 [==============================] - 1029s 442ms/step - loss: 25.3475 - val_loss: 10.0241 - val_edit_distance: 0.1047
Epoch 2/10
2284/2284 [==============================] - 1007s 441ms/step - loss: 4.8511 - val_loss: 4.7007 - val_edit_distance: 0.0433
Epoch 3/10
2284/2284 [==============================] - 1015s 444ms/step - loss: 2.9524 - val_loss: 2.1806 - val_edit_distance: 0.0164
Epoch 4/10
2284/2284 [==============================] - 1007s 440ms/step - loss: 2.1608 - val_loss: 2.0493 - val_edit_distance: 0.0152
Epoch 5/10
2284/2284 [==============================] - 1006s 440ms/step - loss: 1.7302 - val_loss: 1.5993 - val_edit_distance: 0.0122
Epoch 6/10
2284/2284 [==============================] - 1006s 440ms/step - loss: 1.4828 - val_loss: 1.4976 - val_edit_distance: 0.0113
Epoch 7/10
2284/2284 [==============================] - 1014s 443ms/step - loss: 1.2942 - val_loss: 1.5841 - val_edit_distance: 0.0128
Epoch 8/10
2284/2284 [==============================] - 1006s 440ms/step - loss: 1.1755 - val_loss: 1.4460 - val_edit_distance: 0.0120
Epoch 9/10
2284/2284 [==============================] - 1012s 443ms/step - loss: 1.0734 - val_loss: 1.3113 - val_edit_distance: 0.0100
Epoch 10/10
2284/2284 [==============================] - 1012s 443ms/step - loss: 0.9860 - val_loss: 1.2930 - val_edit_distance: 0.0095
228/229 [============================>.] - ETA: 0s
---------------------------------------------------------------------------
FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-1-798da742edaf> in <module>
    181 if __name__ == "__main__":
    182     args = parser.parse_args([] if "__file__" not in globals() else None)
--> 183     main(args)
    184 

2 frames
/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52   try:
     53     ctx.ensure_initialized()
---> 54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:

FailedPreconditionError: Graph execution error:

Detected at node 'IteratorGetNext' defined at (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelapp.py", line 612, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py", line 149, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
      self._run_once()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
      handle._run()
    File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 690, in <lambda>
      lambda f: self._run_callback(functools.partial(callback, future))
    File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 743, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 787, in inner
      self.run()
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 748, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 543, in execute_request
      self.do_execute(
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/ipkernel.py", line 306, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2854, in run_cell
      result = self._run_cell(
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3057, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-1-798da742edaf>", line 183, in <module>
      main(args)
    File "<ipython-input-1-798da742edaf>", line 176, in main
      predictions = model.predict(test)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 2033, in predict
      tmp_batch_outputs = self.predict_function(iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1845, in predict_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1833, in step_function
      data = next(iterator)
Node: 'IteratorGetNext'
Detected at node 'IteratorGetNext' defined at (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 846, in launch_instance
      app.start()
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelapp.py", line 612, in start
      self.io_loop.start()
    File "/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py", line 149, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
      self._run_once()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
      handle._run()
    File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 690, in <lambda>
      lambda f: self._run_callback(functools.partial(callback, future))
    File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 743, in _run_callback
      ret = callback()
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 787, in inner
      self.run()
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 748, in run
      yielded = self.gen.send(value)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 543, in execute_request
      self.do_execute(
    File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
      yielded = next(result)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/ipkernel.py", line 306, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/local/lib/python3.8/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2854, in run_cell
      result = self._run_cell(
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
      return runner(coro)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3057, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-1-798da742edaf>", line 183, in <module>
      main(args)
    File "<ipython-input-1-798da742edaf>", line 176, in main
      predictions = model.predict(test)
    File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 2033, in predict
      tmp_batch_outputs = self.predict_function(iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1845, in predict_function
      return step_function(self, iterator)
    File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1833, in step_function
      data = next(iterator)
Node: 'IteratorGetNext'
2 root error(s) found.
  (0) FAILED_PRECONDITION:  Input dataset was expected to contain 7307 elements but contained only 7305 elements.
	 [[{{node IteratorGetNext}}]]
	 [[Func/RaggedFromSparse/Assert/AssertGuard/else/_1/input/_16/_56]]
  (1) FAILED_PRECONDITION:  Input dataset was expected to contain 7307 elements but contained only 7305 elements.
	 [[{{node IteratorGetNext}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_predict_function_89523]